name: citadel-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - tqdm
  - requests
  - pyyaml
  - joblib
  - cython
  - pillow
  - h5py
  - statsmodels
  - sympy
  - networkx
  - pip:
      - torch
      - torchvision
      - torchaudio
      - tensorboard
      - transformers
      - datasets
      - accelerate
      - scikit-multilearn
      - imbalanced-learn
      - lightning  # PyTorch Lightning
      - huggingface_hub
